### ISSUE TITLE
Make the design of the site more stylish

### ISSUE THREAD

**Issue by icemint0828** [icemint0828/imgedit-wasm#1]
This is an issue for someone I ask.

The design of the site is a bit tacky and we would like to make it more stylish.
You can only change files in docs directory.

**Comment by Shinaco1992** [comment]
I will take up this issue.

**Comment by icemint0828** [comment]
@Shinaco1992
Thank for taking charge of this work!

**Comment by icemint0828** [comment]
The following issues still remain.

* Input form design
* Design of grayscale and reset
* Expansion of drop area
