### ISSUE TITLE
Add file conversion features

### ISSUE THREAD

**Issue by icemint0828** [icemint0828/imgedit-wasm#2]
Imgedit got file conversion features in v1.2.0.
Additional support can be added to this project as well.

* add functions(png, jpeg, gif) to main.go
* add feature as GUI to docs/index.html

~~This issue is stoped until to resolve #1.~~

**Comment by Shinaco1992** [comment]
I'd like to take up this issue.

**Comment by icemint0828** [comment]
@Shinaco1992 
This feature needed byteConverter to be provided in WASM.
The byteConverter is being developed in v1.4.0 and will be ready soon.
Therefore, please give me a few minutes of your time.

Sorry for the inconvenience.

**Comment by icemint0828** [comment]
@Shinaco1992 
Fixed to use ByteConverter(ef61274).
This may make implementation easier.
